apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-backup-script
data:
  mariadb_backup.sh: |
    #!/bin/sh
    # Get current timestamp in human-readable format using date command
    backup_timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
    echo "File creation with timestamp: $backup_timestamp"
    mariadb-dump -h mariadb-service -u root -p$(cat /secrets/ROOT_PASSWORD) --all-databases > "/backup/backup-$backup_timestamp.sql"
    gzip -9 -c "/backup/backup-$backup_timestamp.sql" > "/backup/backup-$backup_timestamp.sql.gz"
