apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup-cronjob
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mariadb-backup
              image: mariadb:11.6.2
              command:
                - "/bin/sh"
                #- "-c"
                - "/backup_script/backup.sh"
                #- "mariadb-dump -h mariadb-service -u root -p$(cat /secrets/ROOT_PASSWORD) --all-databases > /backup/backup-$(date +'%Y%m%d%H%M%S').sql"
              volumeMounts:
                - name: mariadb-secrets
                  mountPath: /secrets
                  readOnly: true
                - name: mariadb-backup-script
                  mountPath: /backup_script
          restartPolicy: OnFailure
          volumes:
            - name: mariadb-secrets
              secret:
                secretName: mariadb-secrets
            - name: mariadb-backup-script
              configMap:
                name: mariadb-backup-script
                defaultMode: 0777
                items:
                  - key: "mariadb_backup.sh"
                    path: "backup.sh"
