kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-service
  labels:
    app.kubernetes.io/name: phpmyadmin
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: phpmyadmin
  ports:
    - nodePort: 30100
      port: 9000
      targetPort: phpmyadmin-port
