apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: phpmyadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.2.2
          ports:
            - name: phpmyadmin-port
              containerPort: 80
          env:
            - name: PMA_HOST
              value: mariadb-service
            - name: PMA_PORT
              value: "3306"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /
              port: phpmyadmin-port
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: phpmyadmin-port
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: phpmyadmin-session-vol
              mountPath: /session
      volumes:
        - name: phpmyadmin-session-vol
          persistentVolumeClaim:
            claimName: phpmyadmin-session-pvc
