apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-session-pvc
  labels:
    recurring-job.longhorn.io/db-snapshots: enabled
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
